import type { Metadata } from 'next';
import './globals.css';
import { inter } from '@/config/fonts';
import { Provider } from '@/components';

export const metadata: Metadata = {
  title: {
    template: '%s - Purple | Shop',
    default: 'Home - Purple | Shop'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
